### get all person
GET http://localhost:3001/api/person

### get by id 1
GET http://localhost:3001/api/person/1

### post new person
POST http://localhost:3001/api/person/
content-type: application/json

{
  "name": "Bruno Hellas",
  "number": "040-123456"
}


### Delete person 3
DELETE http://localhost:3001/api/person/3